name: scout_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.1
  adaptive_theme: ^3.6.0
  flutter_svg: ^2.0.10+1
  animated_toggle_switch: ^0.8.2
  google_fonts: ^6.2.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    


